[package]
name = "tincr"
version = "0.1.0"
authors = ["hochej <37776098+hochej@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chemfiles = "0.9"
ndarray = {version = "0.12", features = ["serde-1"]}
ndarray-linalg = { version = "0.11" }
phf = { version = "0.8.0", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
ron = "0.6.0"
peroxide = "0.27.0"